# Generated by Django 3.2.7 on 2021-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0002_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="blog_api.Category"),
        ),
    ]
